// Code generated by protoc-gen-go. DO NOT EDIT.
// source: meshconfig/meshconfig.proto

package meshconfig

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type MeshConfig struct {
	//policy check的服务器名称
	MixerCheckServer string `protobuf:"bytes,1,opt,name=mixer_check_server,json=mixerCheckServer,proto3" json:"mixer_check_server,omitempty"`
	//report遥测数据的服务器名称
	MixerReportServer string `protobuf:"bytes,2,opt,name=mixer_report_server,json=mixerReportServer,proto3" json:"mixer_report_server,omitempty"`
	//Envoy监听其他服务的端口
	ProxyListenPort int32 `protobuf:"varint,3,opt,name=proxy_listen_port,json=proxyListenPort,proto3" json:"proxy_listen_port,omitempty"`
	//ingress服务的名称
	IngressService string `protobuf:"bytes,4,opt,name=ingress_service,json=ingressService,proto3" json:"ingress_service,omitempty"`
	//访问日志路径
	AccessLogFile string `protobuf:"bytes,5,opt,name=access_log_file,json=accessLogFile,proto3" json:"access_log_file,omitempty"`
	//代理配置
	DefaultConfig *ProxyConfig `protobuf:"bytes,6,opt,name=default_config,json=defaultConfig,proto3" json:"default_config,omitempty"`
	//可信任的域名
	TrustDomain string `protobuf:"bytes,7,opt,name=trust_domain,json=trustDomain,proto3" json:"trust_domain,omitempty"`
	//根命名空间
	RootNamespace        string   `protobuf:"bytes,8,opt,name=root_namespace,json=rootNamespace,proto3" json:"root_namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MeshConfig) Reset()         { *m = MeshConfig{} }
func (m *MeshConfig) String() string { return proto.CompactTextString(m) }
func (*MeshConfig) ProtoMessage()    {}
func (*MeshConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b164ecc8446a59d8, []int{0}
}

func (m *MeshConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MeshConfig.Unmarshal(m, b)
}
func (m *MeshConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MeshConfig.Marshal(b, m, deterministic)
}
func (m *MeshConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MeshConfig.Merge(m, src)
}
func (m *MeshConfig) XXX_Size() int {
	return xxx_messageInfo_MeshConfig.Size(m)
}
func (m *MeshConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_MeshConfig.DiscardUnknown(m)
}

var xxx_messageInfo_MeshConfig proto.InternalMessageInfo

func (m *MeshConfig) GetMixerCheckServer() string {
	if m != nil {
		return m.MixerCheckServer
	}
	return ""
}

func (m *MeshConfig) GetMixerReportServer() string {
	if m != nil {
		return m.MixerReportServer
	}
	return ""
}

func (m *MeshConfig) GetProxyListenPort() int32 {
	if m != nil {
		return m.ProxyListenPort
	}
	return 0
}

func (m *MeshConfig) GetIngressService() string {
	if m != nil {
		return m.IngressService
	}
	return ""
}

func (m *MeshConfig) GetAccessLogFile() string {
	if m != nil {
		return m.AccessLogFile
	}
	return ""
}

func (m *MeshConfig) GetDefaultConfig() *ProxyConfig {
	if m != nil {
		return m.DefaultConfig
	}
	return nil
}

func (m *MeshConfig) GetTrustDomain() string {
	if m != nil {
		return m.TrustDomain
	}
	return ""
}

func (m *MeshConfig) GetRootNamespace() string {
	if m != nil {
		return m.RootNamespace
	}
	return ""
}

type ProxyConfig struct {
	//配置路径
	ConfigPath string `protobuf:"bytes,1,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	//可执行文件路径
	BinaryPath string `protobuf:"bytes,2,opt,name=binary_path,json=binaryPath,proto3" json:"binary_path,omitempty"`
	//服务发现地址
	DiscoveryAddress string `protobuf:"bytes,3,opt,name=discovery_address,json=discoveryAddress,proto3" json:"discovery_address,omitempty"`
	//代理管理端口
	ProxyAdminPort int32 `protobuf:"varint,4,opt,name=proxy_admin_port,json=proxyAdminPort,proto3" json:"proxy_admin_port,omitempty"`
	//bootstrap模板路径
	ProxyBootstrapTemplatePath string `protobuf:"bytes,5,opt,name=proxy_bootstrap_template_path,json=proxyBootstrapTemplatePath,proto3" json:"proxy_bootstrap_template_path,omitempty"`
	//状态端口，一般用于健康检查
	StatusPort           int32    `protobuf:"varint,6,opt,name=status_port,json=statusPort,proto3" json:"status_port,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ProxyConfig) Reset()         { *m = ProxyConfig{} }
func (m *ProxyConfig) String() string { return proto.CompactTextString(m) }
func (*ProxyConfig) ProtoMessage()    {}
func (*ProxyConfig) Descriptor() ([]byte, []int) {
	return fileDescriptor_b164ecc8446a59d8, []int{1}
}

func (m *ProxyConfig) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ProxyConfig.Unmarshal(m, b)
}
func (m *ProxyConfig) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ProxyConfig.Marshal(b, m, deterministic)
}
func (m *ProxyConfig) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ProxyConfig.Merge(m, src)
}
func (m *ProxyConfig) XXX_Size() int {
	return xxx_messageInfo_ProxyConfig.Size(m)
}
func (m *ProxyConfig) XXX_DiscardUnknown() {
	xxx_messageInfo_ProxyConfig.DiscardUnknown(m)
}

var xxx_messageInfo_ProxyConfig proto.InternalMessageInfo

func (m *ProxyConfig) GetConfigPath() string {
	if m != nil {
		return m.ConfigPath
	}
	return ""
}

func (m *ProxyConfig) GetBinaryPath() string {
	if m != nil {
		return m.BinaryPath
	}
	return ""
}

func (m *ProxyConfig) GetDiscoveryAddress() string {
	if m != nil {
		return m.DiscoveryAddress
	}
	return ""
}

func (m *ProxyConfig) GetProxyAdminPort() int32 {
	if m != nil {
		return m.ProxyAdminPort
	}
	return 0
}

func (m *ProxyConfig) GetProxyBootstrapTemplatePath() string {
	if m != nil {
		return m.ProxyBootstrapTemplatePath
	}
	return ""
}

func (m *ProxyConfig) GetStatusPort() int32 {
	if m != nil {
		return m.StatusPort
	}
	return 0
}

func init() {
	proto.RegisterType((*MeshConfig)(nil), "MeshConfig")
	proto.RegisterType((*ProxyConfig)(nil), "ProxyConfig")
}

func init() {
	proto.RegisterFile("meshconfig/meshconfig.proto", fileDescriptor_b164ecc8446a59d8)
}

var fileDescriptor_b164ecc8446a59d8 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x92, 0xdd, 0x6e, 0xd3, 0x40,
	0x10, 0x85, 0x95, 0xd0, 0x06, 0x3a, 0x69, 0xf3, 0xb3, 0xdc, 0x58, 0x20, 0x44, 0xa8, 0x04, 0x44,
	0x80, 0x82, 0x44, 0x9f, 0x20, 0x14, 0x71, 0x55, 0x50, 0xe4, 0x72, 0xbf, 0xda, 0xac, 0x27, 0xf1,
	0x0a, 0xdb, 0x6b, 0xed, 0x4e, 0xaa, 0xe4, 0x15, 0x78, 0x50, 0x9e, 0x03, 0xed, 0x8c, 0x0d, 0xdc,
	0x59, 0xdf, 0xf9, 0xb4, 0x67, 0x74, 0x64, 0x78, 0x5e, 0x63, 0x2c, 0xad, 0x6f, 0x76, 0x6e, 0xff,
	0xf1, 0xdf, 0xe7, 0xaa, 0x0d, 0x9e, 0xfc, 0xf5, 0xef, 0x21, 0xc0, 0x37, 0x8c, 0xe5, 0x2d, 0x43,
	0xf5, 0x01, 0x54, 0xed, 0x8e, 0x18, 0xb4, 0x2d, 0xd1, 0xfe, 0xd4, 0x11, 0xc3, 0x03, 0x86, 0x6c,
	0xb0, 0x18, 0x2c, 0x2f, 0xf2, 0x19, 0x27, 0xb7, 0x29, 0xb8, 0x67, 0xae, 0x56, 0xf0, 0x54, 0xec,
	0x80, 0xad, 0x0f, 0xd4, 0xeb, 0x43, 0xd6, 0xe7, 0x1c, 0xe5, 0x9c, 0x74, 0xfe, 0x3b, 0x98, 0xb7,
	0xc1, 0x1f, 0x4f, 0xba, 0x72, 0x91, 0xb0, 0xd1, 0x29, 0xca, 0x1e, 0x2d, 0x06, 0xcb, 0xf3, 0x7c,
	0xca, 0xc1, 0x1d, 0xf3, 0x8d, 0x0f, 0xa4, 0xde, 0xc2, 0xd4, 0x35, 0xfb, 0x80, 0x31, 0xf2, 0xb3,
	0xce, 0x62, 0x76, 0xc6, 0xef, 0x4e, 0x3a, 0x7c, 0x2f, 0x54, 0xbd, 0x81, 0xa9, 0xb1, 0x36, 0x79,
	0x95, 0xdf, 0xeb, 0x9d, 0xab, 0x30, 0x3b, 0x67, 0xf1, 0x4a, 0xf0, 0x9d, 0xdf, 0x7f, 0x75, 0x15,
	0xaa, 0x1b, 0x98, 0x14, 0xb8, 0x33, 0x87, 0x8a, 0xb4, 0x2c, 0x90, 0x8d, 0x16, 0x83, 0xe5, 0xf8,
	0xd3, 0xe5, 0x6a, 0x93, 0xaa, 0x65, 0x80, 0xfc, 0xaa, 0x73, 0xba, 0x3d, 0x5e, 0xc1, 0x25, 0x85,
	0x43, 0x24, 0x5d, 0xf8, 0xda, 0xb8, 0x26, 0x7b, 0xcc, 0x2f, 0x8f, 0x99, 0x7d, 0x61, 0xa4, 0x5e,
	0xc3, 0x24, 0x78, 0x4f, 0xba, 0x31, 0x35, 0xc6, 0xd6, 0x58, 0xcc, 0x9e, 0x48, 0x7d, 0xa2, 0xdf,
	0x7b, 0x78, 0xfd, 0x6b, 0x08, 0xe3, 0xff, 0x8a, 0xd4, 0x4b, 0x18, 0xcb, 0x19, 0xba, 0x35, 0x54,
	0x76, 0x13, 0x83, 0xa0, 0x8d, 0xa1, 0x32, 0x09, 0x5b, 0xd7, 0x98, 0x70, 0x12, 0x41, 0x46, 0x05,
	0x41, 0x2c, 0xbc, 0x87, 0x79, 0xe1, 0xa2, 0xf5, 0x0f, 0x18, 0x4e, 0xda, 0x14, 0x45, 0x1a, 0x85,
	0xd7, 0xbc, 0xc8, 0x67, 0x7f, 0x83, 0xb5, 0x70, 0xb5, 0x84, 0x99, 0x4c, 0x6f, 0x8a, 0xda, 0x75,
	0xcb, 0x9f, 0xf1, 0xf2, 0x13, 0xe6, 0xeb, 0x84, 0x79, 0xf8, 0x35, 0xbc, 0x10, 0x73, 0xeb, 0x3d,
	0x45, 0x0a, 0xa6, 0xd5, 0x84, 0x75, 0x5b, 0x19, 0x42, 0xb9, 0x44, 0xd6, 0x7d, 0xc6, 0xd2, 0xe7,
	0xde, 0xf9, 0xd1, 0x29, 0xfd, 0xe9, 0x91, 0x0c, 0x1d, 0xa2, 0xf4, 0x8c, 0xb8, 0x07, 0x04, 0xa5,
	0x8e, 0xed, 0x88, 0x7f, 0xbe, 0x9b, 0x3f, 0x01, 0x00, 0x00, 0xff, 0xff, 0x3b, 0xb6, 0x68, 0x21,
	0x9b, 0x02, 0x00, 0x00,
}
