// Code generated by protoc-gen-go. DO NOT EDIT.
// source: mixer/mixer.proto

package mixer

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//状态码
type Code int32

const (
	// HTTP 状态码: 200 OK
	Code_OK Code = 0
	// HTTP 状态码: 499 客户端关闭请求
	Code_CANCELLED Code = 1
	// HTTP 状态码: 500 内部服务器错误
	Code_UNKNOWN Code = 2
	// HTTP 状态码: 400 糟糕的请求
	Code_INVALID_ARGUMENT Code = 3
	// HTTP 状态码: 504 网关超时
	Code_DEADLINE_EXCEEDED Code = 4
	// HTTP 状态码: 404 没有找到
	Code_NOT_FOUND Code = 5
	// HTTP 状态码: 409 冲突
	Code_ALREADY_EXISTS Code = 6
	// HTTP 状态码: 403 禁止
	Code_PERMISSION_DENIED Code = 7
	// HTTP 状态码: 429 过多的请求
	Code_RESOURCE_EXHAUSTED Code = 8
	// HTTP 状态码: 400 遭到的请求
	Code_FAILED_PRECONDITION Code = 9
	// HTTP 状态码: 409 冲突
	Code_ABORTED Code = 10
	// HTTP 状态码: 400 糟糕的请求
	Code_OUT_OF_RANGE Code = 11
	// HTTP 状态码: 501 没有实现
	Code_UNIMPLEMENTED Code = 12
	// HTTP 状态码: 500 内部服务器错误
	Code_INTERNAL Code = 13
	// HTTP 状态码: 503 服务不可用
	Code_UNAVAILABLE Code = 14
	// HTTP 状态码: 500 内部服务器错误
	Code_DATA_LOSS Code = 15
	// HTTP 状态码: 401 权限不足
	Code_UNAUTHENTICATED Code = 16
)

var Code_name = map[int32]string{
	0:  "OK",
	1:  "CANCELLED",
	2:  "UNKNOWN",
	3:  "INVALID_ARGUMENT",
	4:  "DEADLINE_EXCEEDED",
	5:  "NOT_FOUND",
	6:  "ALREADY_EXISTS",
	7:  "PERMISSION_DENIED",
	8:  "RESOURCE_EXHAUSTED",
	9:  "FAILED_PRECONDITION",
	10: "ABORTED",
	11: "OUT_OF_RANGE",
	12: "UNIMPLEMENTED",
	13: "INTERNAL",
	14: "UNAVAILABLE",
	15: "DATA_LOSS",
	16: "UNAUTHENTICATED",
}

var Code_value = map[string]int32{
	"OK":                  0,
	"CANCELLED":           1,
	"UNKNOWN":             2,
	"INVALID_ARGUMENT":    3,
	"DEADLINE_EXCEEDED":   4,
	"NOT_FOUND":           5,
	"ALREADY_EXISTS":      6,
	"PERMISSION_DENIED":   7,
	"RESOURCE_EXHAUSTED":  8,
	"FAILED_PRECONDITION": 9,
	"ABORTED":             10,
	"OUT_OF_RANGE":        11,
	"UNIMPLEMENTED":       12,
	"INTERNAL":            13,
	"UNAVAILABLE":         14,
	"DATA_LOSS":           15,
	"UNAUTHENTICATED":     16,
}

func (x Code) String() string {
	return proto.EnumName(Code_name, int32(x))
}

func (Code) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{0}
}

//属性匹配的状况
type Condition int32

const (
	Condition_CONDITION_UNSPECIFIED Condition = 0
	Condition_ABSENCE               Condition = 1
	Condition_EXACT                 Condition = 2
)

var Condition_name = map[int32]string{
	0: "CONDITION_UNSPECIFIED",
	1: "ABSENCE",
	2: "EXACT",
}

var Condition_value = map[string]int32{
	"CONDITION_UNSPECIFIED": 0,
	"ABSENCE":               1,
	"EXACT":                 2,
}

func (x Condition) String() string {
	return proto.EnumName(Condition_name, int32(x))
}

func (Condition) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{1}
}

type CheckRequest struct {
	//传入需要的变量
	Attributes *CompressedAttributes `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	//每个限额分配的情况
	Quotas               []*CheckRequest_QuotaParams `protobuf:"bytes,2,rep,name=quotas,proto3" json:"quotas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                    `json:"-"`
	XXX_unrecognized     []byte                      `json:"-"`
	XXX_sizecache        int32                       `json:"-"`
}

func (m *CheckRequest) Reset()         { *m = CheckRequest{} }
func (m *CheckRequest) String() string { return proto.CompactTextString(m) }
func (*CheckRequest) ProtoMessage()    {}
func (*CheckRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{0}
}

func (m *CheckRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest.Unmarshal(m, b)
}
func (m *CheckRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest.Marshal(b, m, deterministic)
}
func (m *CheckRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest.Merge(m, src)
}
func (m *CheckRequest) XXX_Size() int {
	return xxx_messageInfo_CheckRequest.Size(m)
}
func (m *CheckRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest proto.InternalMessageInfo

func (m *CheckRequest) GetAttributes() *CompressedAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *CheckRequest) GetQuotas() []*CheckRequest_QuotaParams {
	if m != nil {
		return m.Quotas
	}
	return nil
}

type CheckRequest_QuotaParams struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//分配的限额数量
	Amount int64 `protobuf:"varint,2,opt,name=amount,proto3" json:"amount,omitempty"`
	//当为true时，支持返回比请求数量少的quota
	BestEffort           bool     `protobuf:"varint,3,opt,name=best_effort,json=bestEffort,proto3" json:"best_effort,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckRequest_QuotaParams) Reset()         { *m = CheckRequest_QuotaParams{} }
func (m *CheckRequest_QuotaParams) String() string { return proto.CompactTextString(m) }
func (*CheckRequest_QuotaParams) ProtoMessage()    {}
func (*CheckRequest_QuotaParams) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{0, 0}
}

func (m *CheckRequest_QuotaParams) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckRequest_QuotaParams.Unmarshal(m, b)
}
func (m *CheckRequest_QuotaParams) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckRequest_QuotaParams.Marshal(b, m, deterministic)
}
func (m *CheckRequest_QuotaParams) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckRequest_QuotaParams.Merge(m, src)
}
func (m *CheckRequest_QuotaParams) XXX_Size() int {
	return xxx_messageInfo_CheckRequest_QuotaParams.Size(m)
}
func (m *CheckRequest_QuotaParams) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckRequest_QuotaParams.DiscardUnknown(m)
}

var xxx_messageInfo_CheckRequest_QuotaParams proto.InternalMessageInfo

func (m *CheckRequest_QuotaParams) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckRequest_QuotaParams) GetAmount() int64 {
	if m != nil {
		return m.Amount
	}
	return 0
}

func (m *CheckRequest_QuotaParams) GetBestEffort() bool {
	if m != nil {
		return m.BestEffort
	}
	return false
}

type CompressedAttributes struct {
	Strings              map[string]string     `protobuf:"bytes,1,rep,name=strings,proto3" json:"strings,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	StringMaps           map[string]*StringMap `protobuf:"bytes,2,rep,name=stringMaps,proto3" json:"stringMaps,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CompressedAttributes) Reset()         { *m = CompressedAttributes{} }
func (m *CompressedAttributes) String() string { return proto.CompactTextString(m) }
func (*CompressedAttributes) ProtoMessage()    {}
func (*CompressedAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{1}
}

func (m *CompressedAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CompressedAttributes.Unmarshal(m, b)
}
func (m *CompressedAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CompressedAttributes.Marshal(b, m, deterministic)
}
func (m *CompressedAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CompressedAttributes.Merge(m, src)
}
func (m *CompressedAttributes) XXX_Size() int {
	return xxx_messageInfo_CompressedAttributes.Size(m)
}
func (m *CompressedAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_CompressedAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_CompressedAttributes proto.InternalMessageInfo

func (m *CompressedAttributes) GetStrings() map[string]string {
	if m != nil {
		return m.Strings
	}
	return nil
}

func (m *CompressedAttributes) GetStringMaps() map[string]*StringMap {
	if m != nil {
		return m.StringMaps
	}
	return nil
}

type StringMap struct {
	KeyValue             map[string]string `protobuf:"bytes,1,rep,name=keyValue,proto3" json:"keyValue,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *StringMap) Reset()         { *m = StringMap{} }
func (m *StringMap) String() string { return proto.CompactTextString(m) }
func (*StringMap) ProtoMessage()    {}
func (*StringMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{2}
}

func (m *StringMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StringMap.Unmarshal(m, b)
}
func (m *StringMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StringMap.Marshal(b, m, deterministic)
}
func (m *StringMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StringMap.Merge(m, src)
}
func (m *StringMap) XXX_Size() int {
	return xxx_messageInfo_StringMap.Size(m)
}
func (m *StringMap) XXX_DiscardUnknown() {
	xxx_messageInfo_StringMap.DiscardUnknown(m)
}

var xxx_messageInfo_StringMap proto.InternalMessageInfo

func (m *StringMap) GetKeyValue() map[string]string {
	if m != nil {
		return m.KeyValue
	}
	return nil
}

type Status struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Status) Reset()         { *m = Status{} }
func (m *Status) String() string { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()    {}
func (*Status) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{3}
}

func (m *Status) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Status.Unmarshal(m, b)
}
func (m *Status) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Status.Marshal(b, m, deterministic)
}
func (m *Status) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Status.Merge(m, src)
}
func (m *Status) XXX_Size() int {
	return xxx_messageInfo_Status.Size(m)
}
func (m *Status) XXX_DiscardUnknown() {
	xxx_messageInfo_Status.DiscardUnknown(m)
}

var xxx_messageInfo_Status proto.InternalMessageInfo

func (m *Status) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Status) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type CheckResponse struct {
	Precondition         *CheckResponse_PreconditionResult `protobuf:"bytes,1,opt,name=precondition,proto3" json:"precondition,omitempty"`
	Quotas               []*CheckResponse_QuotaResult      `protobuf:"bytes,2,rep,name=quotas,proto3" json:"quotas,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CheckResponse) Reset()         { *m = CheckResponse{} }
func (m *CheckResponse) String() string { return proto.CompactTextString(m) }
func (*CheckResponse) ProtoMessage()    {}
func (*CheckResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{4}
}

func (m *CheckResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse.Unmarshal(m, b)
}
func (m *CheckResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse.Marshal(b, m, deterministic)
}
func (m *CheckResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse.Merge(m, src)
}
func (m *CheckResponse) XXX_Size() int {
	return xxx_messageInfo_CheckResponse.Size(m)
}
func (m *CheckResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse proto.InternalMessageInfo

func (m *CheckResponse) GetPrecondition() *CheckResponse_PreconditionResult {
	if m != nil {
		return m.Precondition
	}
	return nil
}

func (m *CheckResponse) GetQuotas() []*CheckResponse_QuotaResult {
	if m != nil {
		return m.Quotas
	}
	return nil
}

type CheckResponse_PreconditionResult struct {
	//status返回码是"OK"，则表明前置条件检查通过，其他表明不通过
	Status *Status `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	//结果有效的秒数
	Duration int64 `protobuf:"varint,2,opt,name=duration,proto3" json:"duration,omitempty"`
	//引用的属性
	ReferencedAttributes *ReferencedAttributes `protobuf:"bytes,3,opt,name=referenced_attributes,json=referencedAttributes,proto3" json:"referenced_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CheckResponse_PreconditionResult) Reset()         { *m = CheckResponse_PreconditionResult{} }
func (m *CheckResponse_PreconditionResult) String() string { return proto.CompactTextString(m) }
func (*CheckResponse_PreconditionResult) ProtoMessage()    {}
func (*CheckResponse_PreconditionResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{4, 0}
}

func (m *CheckResponse_PreconditionResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse_PreconditionResult.Unmarshal(m, b)
}
func (m *CheckResponse_PreconditionResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse_PreconditionResult.Marshal(b, m, deterministic)
}
func (m *CheckResponse_PreconditionResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse_PreconditionResult.Merge(m, src)
}
func (m *CheckResponse_PreconditionResult) XXX_Size() int {
	return xxx_messageInfo_CheckResponse_PreconditionResult.Size(m)
}
func (m *CheckResponse_PreconditionResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse_PreconditionResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse_PreconditionResult proto.InternalMessageInfo

func (m *CheckResponse_PreconditionResult) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CheckResponse_PreconditionResult) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CheckResponse_PreconditionResult) GetReferencedAttributes() *ReferencedAttributes {
	if m != nil {
		return m.ReferencedAttributes
	}
	return nil
}

type CheckResponse_QuotaResult struct {
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	//status返回码是"OK"，则表已经有得到限额分配的结果
	Status *Status `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	//分配的限额数量
	GrantedAmount int64 `protobuf:"varint,3,opt,name=granted_amount,json=grantedAmount,proto3" json:"granted_amount,omitempty"`
	//结果有效的秒数
	Duration int64 `protobuf:"varint,4,opt,name=duration,proto3" json:"duration,omitempty"`
	//引用的属性
	ReferencedAttributes *ReferencedAttributes `protobuf:"bytes,5,opt,name=referenced_attributes,json=referencedAttributes,proto3" json:"referenced_attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *CheckResponse_QuotaResult) Reset()         { *m = CheckResponse_QuotaResult{} }
func (m *CheckResponse_QuotaResult) String() string { return proto.CompactTextString(m) }
func (*CheckResponse_QuotaResult) ProtoMessage()    {}
func (*CheckResponse_QuotaResult) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{4, 1}
}

func (m *CheckResponse_QuotaResult) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckResponse_QuotaResult.Unmarshal(m, b)
}
func (m *CheckResponse_QuotaResult) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckResponse_QuotaResult.Marshal(b, m, deterministic)
}
func (m *CheckResponse_QuotaResult) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckResponse_QuotaResult.Merge(m, src)
}
func (m *CheckResponse_QuotaResult) XXX_Size() int {
	return xxx_messageInfo_CheckResponse_QuotaResult.Size(m)
}
func (m *CheckResponse_QuotaResult) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckResponse_QuotaResult.DiscardUnknown(m)
}

var xxx_messageInfo_CheckResponse_QuotaResult proto.InternalMessageInfo

func (m *CheckResponse_QuotaResult) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *CheckResponse_QuotaResult) GetStatus() *Status {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CheckResponse_QuotaResult) GetGrantedAmount() int64 {
	if m != nil {
		return m.GrantedAmount
	}
	return 0
}

func (m *CheckResponse_QuotaResult) GetDuration() int64 {
	if m != nil {
		return m.Duration
	}
	return 0
}

func (m *CheckResponse_QuotaResult) GetReferencedAttributes() *ReferencedAttributes {
	if m != nil {
		return m.ReferencedAttributes
	}
	return nil
}

type ReportRequest struct {
	//传入需要的变量
	Attributes           *CompressedAttributes `protobuf:"bytes,1,opt,name=attributes,proto3" json:"attributes,omitempty"`
	XXX_NoUnkeyedLiteral struct{}              `json:"-"`
	XXX_unrecognized     []byte                `json:"-"`
	XXX_sizecache        int32                 `json:"-"`
}

func (m *ReportRequest) Reset()         { *m = ReportRequest{} }
func (m *ReportRequest) String() string { return proto.CompactTextString(m) }
func (*ReportRequest) ProtoMessage()    {}
func (*ReportRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{5}
}

func (m *ReportRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportRequest.Unmarshal(m, b)
}
func (m *ReportRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportRequest.Marshal(b, m, deterministic)
}
func (m *ReportRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportRequest.Merge(m, src)
}
func (m *ReportRequest) XXX_Size() int {
	return xxx_messageInfo_ReportRequest.Size(m)
}
func (m *ReportRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ReportRequest proto.InternalMessageInfo

func (m *ReportRequest) GetAttributes() *CompressedAttributes {
	if m != nil {
		return m.Attributes
	}
	return nil
}

type ReportResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReportResponse) Reset()         { *m = ReportResponse{} }
func (m *ReportResponse) String() string { return proto.CompactTextString(m) }
func (*ReportResponse) ProtoMessage()    {}
func (*ReportResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{6}
}

func (m *ReportResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReportResponse.Unmarshal(m, b)
}
func (m *ReportResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReportResponse.Marshal(b, m, deterministic)
}
func (m *ReportResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReportResponse.Merge(m, src)
}
func (m *ReportResponse) XXX_Size() int {
	return xxx_messageInfo_ReportResponse.Size(m)
}
func (m *ReportResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ReportResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ReportResponse proto.InternalMessageInfo

type ReferencedAttributes struct {
	AttributeMatches     []*ReferencedAttributes_AttributeMatch `protobuf:"bytes,1,rep,name=attribute_matches,json=attributeMatches,proto3" json:"attribute_matches,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                               `json:"-"`
	XXX_unrecognized     []byte                                 `json:"-"`
	XXX_sizecache        int32                                  `json:"-"`
}

func (m *ReferencedAttributes) Reset()         { *m = ReferencedAttributes{} }
func (m *ReferencedAttributes) String() string { return proto.CompactTextString(m) }
func (*ReferencedAttributes) ProtoMessage()    {}
func (*ReferencedAttributes) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{7}
}

func (m *ReferencedAttributes) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferencedAttributes.Unmarshal(m, b)
}
func (m *ReferencedAttributes) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferencedAttributes.Marshal(b, m, deterministic)
}
func (m *ReferencedAttributes) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferencedAttributes.Merge(m, src)
}
func (m *ReferencedAttributes) XXX_Size() int {
	return xxx_messageInfo_ReferencedAttributes.Size(m)
}
func (m *ReferencedAttributes) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferencedAttributes.DiscardUnknown(m)
}

var xxx_messageInfo_ReferencedAttributes proto.InternalMessageInfo

func (m *ReferencedAttributes) GetAttributeMatches() []*ReferencedAttributes_AttributeMatch {
	if m != nil {
		return m.AttributeMatches
	}
	return nil
}

//此属性是源于Check Request传到服务器端的attributes，所以不需要有值
type ReferencedAttributes_AttributeMatch struct {
	Name                 string    `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Condition            Condition `protobuf:"varint,2,opt,name=condition,proto3,enum=Condition" json:"condition,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *ReferencedAttributes_AttributeMatch) Reset()         { *m = ReferencedAttributes_AttributeMatch{} }
func (m *ReferencedAttributes_AttributeMatch) String() string { return proto.CompactTextString(m) }
func (*ReferencedAttributes_AttributeMatch) ProtoMessage()    {}
func (*ReferencedAttributes_AttributeMatch) Descriptor() ([]byte, []int) {
	return fileDescriptor_8d59ffd13048128a, []int{7, 0}
}

func (m *ReferencedAttributes_AttributeMatch) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReferencedAttributes_AttributeMatch.Unmarshal(m, b)
}
func (m *ReferencedAttributes_AttributeMatch) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReferencedAttributes_AttributeMatch.Marshal(b, m, deterministic)
}
func (m *ReferencedAttributes_AttributeMatch) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReferencedAttributes_AttributeMatch.Merge(m, src)
}
func (m *ReferencedAttributes_AttributeMatch) XXX_Size() int {
	return xxx_messageInfo_ReferencedAttributes_AttributeMatch.Size(m)
}
func (m *ReferencedAttributes_AttributeMatch) XXX_DiscardUnknown() {
	xxx_messageInfo_ReferencedAttributes_AttributeMatch.DiscardUnknown(m)
}

var xxx_messageInfo_ReferencedAttributes_AttributeMatch proto.InternalMessageInfo

func (m *ReferencedAttributes_AttributeMatch) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ReferencedAttributes_AttributeMatch) GetCondition() Condition {
	if m != nil {
		return m.Condition
	}
	return Condition_CONDITION_UNSPECIFIED
}

func init() {
	proto.RegisterEnum("Code", Code_name, Code_value)
	proto.RegisterEnum("Condition", Condition_name, Condition_value)
	proto.RegisterType((*CheckRequest)(nil), "CheckRequest")
	proto.RegisterType((*CheckRequest_QuotaParams)(nil), "CheckRequest.QuotaParams")
	proto.RegisterType((*CompressedAttributes)(nil), "CompressedAttributes")
	proto.RegisterMapType((map[string]*StringMap)(nil), "CompressedAttributes.StringMapsEntry")
	proto.RegisterMapType((map[string]string)(nil), "CompressedAttributes.StringsEntry")
	proto.RegisterType((*StringMap)(nil), "StringMap")
	proto.RegisterMapType((map[string]string)(nil), "StringMap.KeyValueEntry")
	proto.RegisterType((*Status)(nil), "Status")
	proto.RegisterType((*CheckResponse)(nil), "CheckResponse")
	proto.RegisterType((*CheckResponse_PreconditionResult)(nil), "CheckResponse.PreconditionResult")
	proto.RegisterType((*CheckResponse_QuotaResult)(nil), "CheckResponse.QuotaResult")
	proto.RegisterType((*ReportRequest)(nil), "ReportRequest")
	proto.RegisterType((*ReportResponse)(nil), "ReportResponse")
	proto.RegisterType((*ReferencedAttributes)(nil), "ReferencedAttributes")
	proto.RegisterType((*ReferencedAttributes_AttributeMatch)(nil), "ReferencedAttributes.AttributeMatch")
}

func init() {
	proto.RegisterFile("mixer/mixer.proto", fileDescriptor_8d59ffd13048128a)
}

var fileDescriptor_8d59ffd13048128a = []byte{
	// 931 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x55, 0xdd, 0x6e, 0xe3, 0x44,
	0x18, 0xad, 0x93, 0x26, 0x6d, 0xbe, 0xfc, 0x74, 0x3a, 0xdb, 0x2e, 0x59, 0xdf, 0x6c, 0xb1, 0x58,
	0x29, 0x5a, 0x24, 0x23, 0xc2, 0x8f, 0xd0, 0x82, 0x90, 0x66, 0xed, 0xe9, 0xae, 0xa9, 0x33, 0xce,
	0x8e, 0xed, 0x52, 0xb8, 0xc0, 0x72, 0x9b, 0x69, 0x37, 0xea, 0x26, 0xce, 0xda, 0x0e, 0xa2, 0x37,
	0xbc, 0x09, 0x37, 0xbc, 0x04, 0xe2, 0x31, 0x90, 0x78, 0x1e, 0x84, 0xc6, 0x76, 0x1c, 0xa7, 0x44,
	0x88, 0x15, 0x37, 0xd1, 0xcc, 0xf7, 0x73, 0x72, 0x8e, 0xe7, 0x7c, 0x33, 0x70, 0x38, 0x9b, 0xfe,
	0x24, 0xe2, 0x8f, 0xb2, 0x5f, 0x7d, 0x11, 0x47, 0x69, 0xa4, 0xfd, 0xa9, 0x40, 0xc7, 0x78, 0x2d,
	0xae, 0x6e, 0xb9, 0x78, 0xbb, 0x14, 0x49, 0x8a, 0x3f, 0x03, 0x08, 0xd3, 0x34, 0x9e, 0x5e, 0x2e,
	0x53, 0x91, 0xf4, 0x95, 0x13, 0x65, 0xd0, 0x1e, 0x1e, 0xeb, 0x46, 0x34, 0x5b, 0xc4, 0x22, 0x49,
	0xc4, 0x84, 0x94, 0x49, 0x5e, 0x29, 0xc4, 0x1f, 0x43, 0xf3, 0xed, 0x32, 0x4a, 0xc3, 0xa4, 0x5f,
	0x3b, 0xa9, 0x0f, 0xda, 0xc3, 0x47, 0x7a, 0x15, 0x55, 0x7f, 0x25, 0x73, 0xe3, 0x30, 0x0e, 0x67,
	0x09, 0x2f, 0x0a, 0xd5, 0xef, 0xa1, 0x5d, 0x09, 0x63, 0x0c, 0xbb, 0xf3, 0x70, 0x26, 0xb2, 0xbf,
	0x6c, 0xf1, 0x6c, 0x8d, 0x1f, 0x42, 0x33, 0x9c, 0x45, 0xcb, 0x79, 0xda, 0xaf, 0x9d, 0x28, 0x83,
	0x3a, 0x2f, 0x76, 0xf8, 0x31, 0xb4, 0x2f, 0x45, 0x92, 0x06, 0xe2, 0xfa, 0x3a, 0x8a, 0xd3, 0x7e,
	0xfd, 0x44, 0x19, 0xec, 0x73, 0x90, 0x21, 0x9a, 0x45, 0xb4, 0x5f, 0x6b, 0x70, 0xb4, 0x8d, 0x33,
	0xfe, 0x0a, 0xf6, 0x92, 0x34, 0x9e, 0xce, 0x6f, 0xa4, 0x36, 0x49, 0x54, 0xdb, 0xaa, 0x4d, 0x77,
	0xf3, 0x22, 0x3a, 0x4f, 0xe3, 0x3b, 0xbe, 0x6a, 0xc1, 0x14, 0x20, 0x5f, 0x8e, 0xc2, 0xc5, 0x4a,
	0xe9, 0x93, 0x7f, 0x03, 0x90, 0x75, 0x39, 0x46, 0xa5, 0x51, 0x7d, 0x06, 0x9d, 0x2a, 0x3e, 0x46,
	0x50, 0xbf, 0x15, 0x77, 0x85, 0x72, 0xb9, 0xc4, 0x47, 0xd0, 0xf8, 0x31, 0x7c, 0xb3, 0x14, 0x99,
	0xee, 0x16, 0xcf, 0x37, 0xcf, 0x6a, 0x5f, 0x28, 0xaa, 0x05, 0x07, 0xf7, 0xa0, 0xb7, 0xb4, 0x9f,
	0x54, 0xdb, 0xdb, 0x43, 0x58, 0xb3, 0xa9, 0x40, 0x69, 0x3f, 0x43, 0xab, 0x8c, 0xe3, 0x4f, 0x61,
	0xff, 0x56, 0xdc, 0x9d, 0x67, 0x5d, 0xf9, 0x97, 0xe9, 0xaf, 0xbb, 0xf4, 0xb3, 0x22, 0x95, 0x6b,
	0x29, 0x2b, 0xd5, 0x2f, 0xa1, 0xbb, 0x91, 0x7a, 0x17, 0x29, 0xda, 0xe7, 0xd0, 0x74, 0xd3, 0x30,
	0x5d, 0x66, 0x67, 0x7f, 0x15, 0x4d, 0xca, 0xb3, 0x97, 0x6b, 0xdc, 0x87, 0xbd, 0x99, 0x48, 0x92,
	0xf0, 0x66, 0xd5, 0xb9, 0xda, 0x6a, 0x7f, 0xd5, 0xa1, 0x5b, 0xb8, 0x2b, 0x59, 0x44, 0xf3, 0x44,
	0x60, 0x0a, 0x9d, 0x45, 0x2c, 0xae, 0xa2, 0xf9, 0x64, 0x9a, 0x4e, 0xa3, 0x79, 0x61, 0xdb, 0xf7,
	0xf5, 0x8d, 0x2a, 0x7d, 0x5c, 0x29, 0xe1, 0x22, 0x59, 0xbe, 0x49, 0xf9, 0x46, 0x1b, 0x1e, 0xde,
	0x33, 0xb1, 0x7a, 0x0f, 0x20, 0xb3, 0x6b, 0xd1, 0xb9, 0x72, 0xf1, 0x2f, 0x0a, 0xe0, 0x7f, 0x02,
	0xe3, 0xc7, 0xd0, 0x4c, 0x32, 0x6d, 0x05, 0x97, 0x3d, 0x3d, 0x97, 0xca, 0x8b, 0x30, 0x56, 0x61,
	0x7f, 0xb2, 0x8c, 0xc3, 0x8c, 0x6e, 0x6e, 0xee, 0x72, 0x8f, 0xbf, 0x81, 0xe3, 0x58, 0x5c, 0x8b,
	0x58, 0xcc, 0xaf, 0xc4, 0x24, 0xa8, 0x8c, 0x63, 0xbd, 0x18, 0x47, 0x5e, 0x66, 0x2b, 0xe3, 0x78,
	0x14, 0x6f, 0x89, 0xaa, 0x7f, 0x28, 0xc5, 0x98, 0x15, 0xc4, 0xb6, 0x8d, 0xd9, 0x9a, 0x6c, 0x6d,
	0x3b, 0xd9, 0x27, 0xd0, 0xbb, 0x89, 0xc3, 0x79, 0x2a, 0xd9, 0xe4, 0xf3, 0x58, 0xcf, 0x28, 0x77,
	0x8b, 0x28, 0xc9, 0xc7, 0xb2, 0xaa, 0x69, 0xf7, 0xbf, 0x6a, 0x6a, 0xbc, 0xb3, 0x26, 0xed, 0x14,
	0xba, 0x5c, 0x2c, 0xa2, 0x38, 0xfd, 0x7f, 0x97, 0x96, 0x86, 0xa0, 0xb7, 0xc2, 0xc9, 0x4f, 0x58,
	0xfb, 0x5d, 0x81, 0xa3, 0x6d, 0x44, 0xf0, 0x2b, 0x38, 0x2c, 0x1b, 0x83, 0x59, 0x98, 0x5e, 0xbd,
	0x16, 0xab, 0x1b, 0xe4, 0x83, 0xad, 0xd4, 0xf5, 0x72, 0x39, 0x92, 0xd5, 0x1c, 0x85, 0x1b, 0x7b,
	0x91, 0xa8, 0x0c, 0x7a, 0x9b, 0x35, 0x5b, 0xcf, 0x66, 0x00, 0xad, 0xb5, 0xaf, 0xe5, 0xf1, 0xf4,
	0x86, 0xa0, 0x1b, 0xa5, 0xdb, 0xd6, 0xc9, 0xa7, 0xbf, 0xd5, 0x60, 0xd7, 0x90, 0x93, 0xd3, 0x84,
	0x9a, 0x73, 0x86, 0x76, 0x70, 0x17, 0x5a, 0x06, 0x61, 0x06, 0xb5, 0x6d, 0x6a, 0x22, 0x05, 0xb7,
	0x61, 0xcf, 0x67, 0x67, 0xcc, 0xf9, 0x96, 0xa1, 0x1a, 0x3e, 0x02, 0x64, 0xb1, 0x73, 0x62, 0x5b,
	0x66, 0x40, 0xf8, 0x0b, 0x7f, 0x44, 0x99, 0x87, 0xea, 0xf8, 0x18, 0x0e, 0x4d, 0x4a, 0x4c, 0xdb,
	0x62, 0x34, 0xa0, 0x17, 0x06, 0xa5, 0x26, 0x35, 0xd1, 0xae, 0x04, 0x62, 0x8e, 0x17, 0x9c, 0x3a,
	0x3e, 0x33, 0x51, 0x03, 0x63, 0xe8, 0x11, 0x9b, 0x53, 0x62, 0x7e, 0x17, 0xd0, 0x0b, 0xcb, 0xf5,
	0x5c, 0xd4, 0x94, 0x9d, 0x63, 0xca, 0x47, 0x96, 0xeb, 0x5a, 0x0e, 0x0b, 0x4c, 0xca, 0x2c, 0x6a,
	0xa2, 0x3d, 0xfc, 0x10, 0x30, 0xa7, 0xae, 0xe3, 0x73, 0x43, 0x02, 0xbe, 0x24, 0xbe, 0xeb, 0x51,
	0x13, 0xed, 0xe3, 0xf7, 0xe0, 0xc1, 0x29, 0xb1, 0x6c, 0x6a, 0x06, 0x63, 0x4e, 0x0d, 0x87, 0x99,
	0x96, 0x67, 0x39, 0x0c, 0xb5, 0x24, 0x49, 0xf2, 0xdc, 0xe1, 0xb2, 0x0a, 0x30, 0x82, 0x8e, 0xe3,
	0x7b, 0x81, 0x73, 0x1a, 0x70, 0xc2, 0x5e, 0x50, 0xd4, 0xc6, 0x87, 0xd0, 0xf5, 0x99, 0x35, 0x1a,
	0xdb, 0x54, 0x32, 0xa6, 0x26, 0xea, 0xe0, 0x0e, 0xec, 0x5b, 0xcc, 0xa3, 0x9c, 0x11, 0x1b, 0x75,
	0xf1, 0x01, 0xb4, 0x7d, 0x46, 0xce, 0x89, 0x65, 0x93, 0xe7, 0x36, 0x45, 0x3d, 0xc9, 0xdd, 0x24,
	0x1e, 0x09, 0x6c, 0xc7, 0x75, 0xd1, 0x01, 0x7e, 0x00, 0x07, 0x3e, 0x23, 0xbe, 0xf7, 0x92, 0x32,
	0xcf, 0x32, 0x88, 0x84, 0x40, 0x4f, 0xbf, 0x86, 0x56, 0xf9, 0x45, 0xf1, 0x23, 0x38, 0x2e, 0x09,
	0x05, 0x3e, 0x73, 0xc7, 0xd4, 0xb0, 0x4e, 0xa5, 0x9a, 0x9d, 0x9c, 0x9c, 0x4b, 0x99, 0x41, 0x91,
	0x82, 0x5b, 0xd0, 0xa0, 0x17, 0xc4, 0xf0, 0x50, 0x6d, 0xf8, 0x03, 0x34, 0x46, 0xf2, 0x4d, 0xc5,
	0x03, 0x68, 0x64, 0x37, 0x06, 0xee, 0x6e, 0x3c, 0x7f, 0x6a, 0x6f, 0xf3, 0x22, 0xd1, 0x76, 0xf0,
	0x87, 0xd0, 0xcc, 0xad, 0x87, 0x7b, 0xfa, 0x86, 0x97, 0xd5, 0x03, 0xfd, 0x9e, 0x27, 0x77, 0x2e,
	0x9b, 0xd9, 0x5b, 0xfd, 0xc9, 0xdf, 0x01, 0x00, 0x00, 0xff, 0xff, 0xc9, 0x19, 0x84, 0x85, 0xc0,
	0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// MixerClient is the client API for Mixer service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type MixerClient interface {
	//在操作前检查前置条件和限额分配
	Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error)
	//报告遥测数据
	Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error)
}

type mixerClient struct {
	cc grpc.ClientConnInterface
}

func NewMixerClient(cc grpc.ClientConnInterface) MixerClient {
	return &mixerClient{cc}
}

func (c *mixerClient) Check(ctx context.Context, in *CheckRequest, opts ...grpc.CallOption) (*CheckResponse, error) {
	out := new(CheckResponse)
	err := c.cc.Invoke(ctx, "/Mixer/Check", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *mixerClient) Report(ctx context.Context, in *ReportRequest, opts ...grpc.CallOption) (*ReportResponse, error) {
	out := new(ReportResponse)
	err := c.cc.Invoke(ctx, "/Mixer/Report", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// MixerServer is the server API for Mixer service.
type MixerServer interface {
	//在操作前检查前置条件和限额分配
	Check(context.Context, *CheckRequest) (*CheckResponse, error)
	//报告遥测数据
	Report(context.Context, *ReportRequest) (*ReportResponse, error)
}

// UnimplementedMixerServer can be embedded to have forward compatible implementations.
type UnimplementedMixerServer struct {
}

func (*UnimplementedMixerServer) Check(ctx context.Context, req *CheckRequest) (*CheckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Check not implemented")
}
func (*UnimplementedMixerServer) Report(ctx context.Context, req *ReportRequest) (*ReportResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Report not implemented")
}

func RegisterMixerServer(s *grpc.Server, srv MixerServer) {
	s.RegisterService(&_Mixer_serviceDesc, srv)
}

func _Mixer_Check_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixerServer).Check(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mixer/Check",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixerServer).Check(ctx, req.(*CheckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Mixer_Report_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReportRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(MixerServer).Report(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Mixer/Report",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(MixerServer).Report(ctx, req.(*ReportRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _Mixer_serviceDesc = grpc.ServiceDesc{
	ServiceName: "Mixer",
	HandlerType: (*MixerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Check",
			Handler:    _Mixer_Check_Handler,
		},
		{
			MethodName: "Report",
			Handler:    _Mixer_Report_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "mixer/mixer.proto",
}
